# Generated by Django 4.1.1 on 2023-05-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('location', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sample.patient')),
                ('problem', models.TextField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            bases=('sample.patient',),
        ),
    ]
