# Generated by Django 4.0.4 on 2022-05-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(default='10/01/2022')),
                ('first_name', models.CharField(max_length=20)),
                ('median_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=5)),
                ('date_of_birth', models.DateField(default='10/01/2022')),
                ('martial_status', models.CharField(max_length=10)),
                ('occupation', models.CharField(default='', max_length=19)),
                ('religion', models.CharField(default='', max_length=15)),
                ('address', models.TextField(default='Ablekuma-Obelu behind the Mosque')),
                ('mobile', models.CharField(default='0555555555', max_length=10)),
                ('email', models.CharField(default='', max_length=50)),
                ('relative_name', models.CharField(max_length=50)),
                ('relative_address', models.TextField(default='Ablekuma - Newtown, after the taxi rank')),
                ('relative_contact', models.CharField(default='0550000000', max_length=10)),
                ('nhis_number', models.CharField(default='22222222', max_length=8)),
            ],
        ),
    ]
